version: '3'
services:
  app:
    hostname: app-server
    build: ./app
    volumes:
      - ./app:/app
      - socket:/tmp
    container_name: 'app-server'
    ports:
      - '5000:5000'
    networks:
      - bookshelf-network
    command: uwsgi --ini /app/uwsgi.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: 'bookshelf-nginx'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    networks:
      - bookshelf-network

networks:
  bookshelf-network:
    driver: bridge

volumes:
  socket:
  db_volume:
