version: '3'
services:
  bookshelf-app:
    hostname: bookshelf-app-server
    build: ./app
    volumes:
      - ./app:/app
      - socket:/tmp
    container_name: 'bookshelf-app-server'
    ports:
      - '5000:5000'
    networks:
      - bookshelf-network
    environment:
      - TZ=Asia/Tokyo
    command: uwsgi --ini /app/uwsgi.ini

  bookshelf-web:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: 'bookshelf-nginx'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    environment:
      - TZ=Asia/Tokyo
    networks:
      - bookshelf-network

  bookshelf-mysql-db:
    container_name: "bookshelf-mysql-db"
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=+09:00
    volumes:
      - db_volume:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    # Set up mysql database name and password
    env_file: ./.env
    ports:
      - 3306:3306
    networks:
      - bookshelf-network

networks:
  bookshelf-network:
    driver: bridge

volumes:
  socket:
  db_volume:
