from .main_view import main as main_view_main
from .book_view import main as book_view_main
from .borrow_view import main as borrow_view_main
from .maintenance_view import main as maintenance_view_main
from .member_view import main as member_view_main
from .genre_view import main as genre_view_main
from .get_book_with_isbn_view import main as get_book_with_isbn_view_main
from .signup_view import main as signup_view_main
from .login_view import main as login_view_main
from .logout_view import main as logout_view_main
from .export_books_view import main as export_books_view_main
from .regist_member_with_csv_view import main as regist_member_with_csv_view_main
from .test_view import main as test_view_main
